FROM nginx

MAINTAINER jerrychir <jerrychir@163.com>

WORKDIR /usr/src/app/

COPY ./config/nginx.conf /etc/nginx/conf.d/default.conf

COPY ./dist  /usr/share/nginx/html/

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
